language: cpp
before_script:
    - ./install-cmake.sh
    - export PATH=$PWD/cmake/bin:${PATH}
    - sudo apt-get update -qq
    - sudo apt-get install -y git dpkg-dev make g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev
    - sudo apt-get install -y gfortran libssl-dev libpcre3-dev xlibmesa-glu-dev libglew1.5-dev libftgl-dev libmysqlclient-dev libfftw3-dev cfitsio-dev graphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python-dev libxml2-dev libkrb5-dev libgsl0-dev libqt4-dev
    - ./install-root_CMAKE.sh
    - . ./root/bin/thisroot.sh
